<?php 
	$product = $this->product;
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$session_lang=new Zend_Session_Namespace('lang');
	$currentlang = $session_lang->lang_id;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	//$base_url = Application_Form_FrmMessage::getUrl("/");
	$menu_info = $this->menu_info; 
	$db = new Application_Model_DbTable_DbGlobalSelect();
	$articleperpage = $db->getWebsiteSetting("items_per_page");
	$bannerlist = $db->getWebsiteSetting("banner");
	
	$loadmordata= $articleperpage['value'];
	
	$banner = explode(",", $bannerlist['value']);
if(!empty($this->param['param'])){
?>
<title><?php echo $menu_info['title_menu'];?></title>
	 
				<?php if ($menu_info['menu_type_id']==1){ //category blog
					if(!empty($menu_info['category_id'])){
						$aticle = $db->getArcticleByCate($menu_info['category_id']);?>
								
					<?php }?>
				<?php }else if ($menu_info['menu_type_id']==2){//category list
									$article = $db->getArcticleByCateForlistAll($menu_info['category_id']);
									$countarticle = $db->countarticle($menu_info['category_id']);
									$cateinfo = $db->getCategoryByID($menu_info['category_id']);
									
									$limits = $db->getWebsiteSetting("items_per_page");
									$paginator = Zend_Paginator::factory($article);
									$paginator->setDefaultItemCountPerPage($limits['value']);
									$allItems = $paginator->getTotalItemCount();
									$countPages= $paginator->count();
									$p = Zend_Controller_Front::getInstance()->getRequest()->getParam('pages');
										
									if(isset($p))
									{
										$paginator->setCurrentPageNumber($p);
									} else $paginator->setCurrentPageNumber(1);
									
									$currentPage = $paginator->getCurrentPageNumber();
										
									$articless  = $paginator;
// 									$this->view->countItems = $allItems;
// 									$this->view->countPages = $countPages;
// 									$this->view->currentPage = $currentPage;
									
									if($currentPage == $countPages)
									{
										$nextPage = $countPages;
										$previousPage = $currentPage-1;
									}
									else if($currentPage == 1)
									{
										$nextPage = $currentPage+1;
										$previousPage = 1;
									}
									else {
										$nextPage = $currentPage+1;
										$previousPage = $currentPage-1;
									}
								?>
								<!-- Breadcrumb Area Start-->
								<div class="breadcrumb-area bg-8">	
									<div class="container">
										<div class="row">
											<div class="col-md-8">
												<div class="breadcrumb-text text-left">
													<h2><?php echo $menu_info['title_menu'];?></h2>
													<div class="breadcrumb-bar">
													<?php if (!empty($cateinfo['sub_title'])){?>
														<p class="subtitle"><?php echo $cateinfo['sub_title'];?></p>
													<?php }else{?>
													
														<ul class="breadcrumb">
															<li><a href="<?php echo $this->baseUrl();?>"><?php echo $tr->translate("HOME");?></a></li>
															<li><?php echo $menu_info['title_menu'];?></li>
														</ul>
													<?php }?>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<!-- Breadcrumb Area End -->
						        <!-- Blog Section Area Start -->
						        <div class="blog-section-area ptb-50">
						            <div class="container">
						                <div class="row">
						                   <div class="col-md-8 col-sm-12 col-xs-12">
						                        <div class="single-blog-post-wrapper">
						                        <?php if(!empty($articless)) foreach($articless as $article){ ?>
						                            <div class="single-blog-post col-md-6 col-sm-12 col-xs-12">
						                            	<div class="list">
							                                <div class="blog-image">
							                                    <a href="<?php echo $this->baseUrl()."/page/index?article=".$article['alias_article'].".html"; ?>">
							                                    <?php if(!empty($article['image_feature'])){?>
																	<img src="<?php echo $this->baseUrl()."/images/article/".$article['image_feature'];?>"/>
																<?php }else{?>
																	<img src="<?php echo $this->baseUrl()."/images/noimage.jpg";?>"/>
																<?php }?>
							                                    </a>
							                                </div>
							                                <div class="blog-post-text">
							                                    <h4><a href="<?php echo $this->baseUrl()."/page/index?article=".$article['alias_article'].".html"; ?>"><?php echo $article['title'];?></a></h4>
							                                   <!-- <div class="blog-post-meta">
								                                    <span><i class="fa fa-calendar"></i> <span><?php //echo date("d-M-Y",strtotime($article['create_date']));?></span></span>
								                                </div> -->  
							                                    <p>
							                                     <?php
																		echo mb_substr($article['description'],0,100, "utf-8")."...";
																	?> 
																</p>
																<div class="readmore">
							                                    <a href="<?php echo $this->baseUrl()."/page/index?article=".$article['alias_article'].".html"; ?>" class="default-btn"><span><?php echo $tr->translate("READ_MORE")?></span></a>
							                               		</div>
							                                </div>
						                                </div>
						                            </div>
						                            <?php }?>
						                        </div>
						                        <?php 
						                        if($countPages>1){ 
												 	$statpage = $currentPage - 5;
												 	$endpage = $currentPage + 5;
												 	if ($currentPage<=5){
												 		$statpage = 1;
												 		$endpage =10;
												 	}
						                        }
						                        if (!empty($countPages)){
												 ?> 
						                        <div class="col-md-12 col-sm-12 col-xs-12 pagination-wrapper fix">
						                            <div class="pagination-content">
						                            <?php if($countPages>1){ ?>
						                                <ul class="pagination">
							                                 <li class="<?php if($currentPage==1){ echo "active";}?>">
							                               	  	<a href="<?php echo $this->baseUrl()."/page/index?param=".$this->param['param']."&pages=".$previousPage;?>"><i class="fa fa-angle-left"></i></a>
							                                 </li>
						                                    <?php  $i=0; for( $i=1; $i<=$countPages; $i++){?>
									           			 	<?php if ($statpage<=$i && $endpage>=$i){?>
		                                   					 <li class="<?php if($i==$currentPage){ echo "active";}?>">
		                                   					 	<a href="<?php echo $this->baseUrl()."/page/index?param=".$this->param['param']."&pages=".$i;?>"><?php echo $i;?></a>
		                                   					 </li>
		                                                 <?php }}?>
		                                                 <li class="<?php if($countPages==$currentPage){ echo "active"; }?>">
							                               	  	<a "href="<?php echo $this->baseUrl()."/page/index?param=".$this->param['param']."&pages=".$nextPage;?>"><i class="fa fa-angle-right"></i></a>
							                                 </li>
						                                </ul>
						                           		<?php }?>
						                            </div>
						                        </div>
						                        <?php }?>
						                    </div>
						                    <div class="col-md-4 col-sm-12 col-xs-12">
						                 	   <?php if (!empty($banner)){?>
												<div class="blog-advertise">
													<?php foreach ($banner as $rs){?>
													<div class="row_advertise pb-20"> 
														<img src="<?php echo $this->baseUrl()."/images/banner/".$rs;?>" class="ad_img" />
													</div>
													<?php }?>
												</div>
												<?php }?>
											</div>
						                </div>
						            </div>
						        </div>
						        <!-- Blog Section Area End -->
				<?php }else if ($menu_info['menu_type_id']==3){//sigle aticle
						$aticle = $db->getAticleByID($menu_info['article_id']);
						$homecategory = $db->getWebsiteSetting("homecategorycontent");
						$lastestart="";
						$cateinfo='';
						if (!empty($homecategory['value'])){
							$cateinfo = $db->getCategoryByID($homecategory['value']);
						$lastestart = $db->getArcticleByCateLastesArticle($homecategory['value'],$menu_info['article_id']);
						}
						?>
					<!-- Breadcrumb Area Start-->
					<div class="breadcrumb-area bg-8">	
						<div class="container ">
							<div class="row">
								<div class="col-md-6">
									<div class="breadcrumb-text text-left">
										<h2><?php echo $menu_info['title_menu'];?></h2>
										<div class="breadcrumb-bar">
											<ul class="breadcrumb">
												<li><a href="<?php echo $this->baseUrl();?>"><?php echo $tr->translate("HOME");?></a></li>
												<li><?php echo $menu_info['title_menu'];?></li>
											</ul>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Breadcrumb Area End -->
					<div class="sigle_article">
					 	 <div class="container siglearticle" >
					        <!-- Blog Section Area Start -->
					        <div class="blog-section-area ptb-20" >
					            <div class="container">
					                <div class="row">
			                   		   <div class="col-md-8 col-sm-12 col-xs-12">
					                        <div class="single-blog-post blog-details">
					                            <div class="blog-post-text">
					                               <h4><?php echo $aticle['title'];?></h4>
					                               <div class="article_desc">
					                               <?php echo $aticle['description'];?>
					                               </div>
					                            </div>
					                        </div>
					                    </div>
				                      	<div class="col-md-4 col-sm-12 col-xs-12">
				                   			<?php if (!empty($banner)){?>
											<div class="blog-advertise">
												<?php foreach ($banner as $rs){?>
												<div class="row_advertise pb-20"> 
													<img src="<?php echo $this->baseUrl()."/images/banner/".$rs;?>" class="ad_img" />
												</div>
												<?php }?>
											</div>
											<?php }?>
				                   		 </div>
					                </div>
					            </div>
					        </div>
					        <!-- Blog Section Area End -->
				        </div>
				    </div>
				<?php }else if ($menu_info['menu_type_id']==4){//Contacts
				$session_message_session = new Zend_Session_Namespace('sentmail_msg');
				$message = $session_message_session->message;
				$session_message_session->unsetAll();
				$contact = $db->getMenuContactByMenID($menu_info['id']);?>
						<!-- Breadcrumb Area Start-->
								<div class="breadcrumb-area bg-8">	
									<div class="container">
										<div class="row">
											<div class="col-md-4">
												<div class="breadcrumb-text text-left">
													<h2><?php echo $menu_info['title_menu'];?></h2>
													<div class="breadcrumb-bar">
														<ul class="breadcrumb">
															<li><a href="<?php echo $this->baseUrl();?>"><?php echo $tr->translate("HOME");?></a></li>
															<li><?php echo $menu_info['title_menu'];?></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<!-- Breadcrumb Area End -->
						        <!-- Contact Information Area Start -->
						        <div class="contact-information-area pt-20">
						            <div class="container">
						            	<div class="row">
						                    <div class="col-lg-12 col-md-12">
						                        <div class="section-title-two">
						                            <h3><span class="icon icon-Info"></span> <?php echo $tr->translate("CONTACT_INFOMATION");?></h3>
						                        </div>
						                    </div>
						                </div>
						                <div class="row">
						                    <div class="col-md-4 col-sm-4">
						                        <div class="single-c-info">
						                            <span class="icon icon-Phone"></span>
						                            <h5><?php echo $tr->translate("PHONE");?></h5>
						                            <div class="c-divider"></div>
						                            <span><?php echo $contact['tel']?></span>
						                        </div>
						                    </div>
						                    <div class="col-md-4 col-sm-4">
						                        <div class="single-c-info">
						                            <span class="icon icon-Pointer"></span>
						                            <h5><?php echo $tr->translate("ADDRESS");?></h5>
						                            <div class="c-divider"></div>
						                            <span><?php echo $contact['address']?></span>
						                        </div>
						                    </div>
						                    <div class="col-md-4 col-sm-4">
						                        <div class="single-c-info">
						                            <span class="icon icon-Phone"></span>
						                            <h5><?php echo $tr->translate("EMAIL");?></h5>
						                            <div class="c-divider"></div>
						                            <span><?php echo $contact['email']?></span>
						                        </div>
						                    </div>
						                </div>
						            </div>
						        </div>
						        <!-- Contact Information Area End -->
						        <!-- Contact Form Area Start -->
						        <div class="contact-form-area pt-20 pb-20">
						            <div class="container">
						            	<div class="col-md-6 col-sm-6">
							                <div class="row">
							                    <div class="col-lg-12 col-md-12">
							                        <div class="section-title-two">
							                            <h3><span class="icon icon-Info"></span> <?php echo $tr->translate("CONTACT_FORM");?></h3>
							                        </div>
							                    </div>
							                </div>
							                <div class="contact-form-wrapper fix">
							                    <form id="contact-form" onsubmit="return validateFormContact(this);" action="<?php echo $this->baseUrl().'/index/contact-form-send-mail'?>" method="post">
							                        <div class="row">
							                            <div class="col-md-6">
							                                <input type="text" name="name" id="name" placeholder="<?php echo $tr->translate("NAME");?>" title="<?php echo $tr->translate("NAME");?>">
							                            </div>
							                            <div class="col-md-6">
							                                <input type="text" name="email" id="email" placeholder="<?php echo $tr->translate("EMAIL");?>" title="<?php echo $tr->translate("EMAIL");?>">
							                            </div>
							                            <div class="col-md-6">
							                                <input type="text" name="telephone" id="telephone" placeholder="<?php echo $tr->translate("PHONE");?>" title="<?php echo $tr->translate("PHONE");?>">
							                            </div>
							                            <div class="col-md-6">
							                                <input type="text" name="subject" id="subject" placeholder="<?php echo $tr->translate("SUBJECT");?>">
							                            </div>
							                        </div>
							                        <textarea name="comment" id="comment" cols="30" rows="10" placeholder="<?php echo $tr->translate("COMMENT");?>" title="<?php echo $tr->translate("COMMENT");?>"></textarea>
							                        <button type="submit" class="submit-btn default-btn gradient">
							                            <span><?php echo $tr->translate("SUBMIT");?></span>
							                        </button>
							                        <p id="message" class="form-messege"><?php if(!empty($message)){ echo $message; } ?></p>
							                    </form>
							                    <script> 
													function validateFormContact(form){
													var message = document.getElementById('message');
													  re = /^\w+$/;
													  if(form.name.value==""){
														  message.innerHTML = "Please fill your Name !";
													      form.name.focus();
													      return false;
													  }else if(form.email.value == "") {
													      message.innerHTML = "Please fill your email address !";
													      form.email.focus();
													      return false;
													  }else if(form.subject.value == "") {
													      message.innerHTML = "Please fill your subject address !";
													      form.email.focus();
													      return false;
													   }else if(form.comment.value == "") {
														      message.innerHTML = "Please fill your comment !";
														      form.comment.focus();
														      return false;
												        }
													  return true;
												}
												</script>
							                </div>
							              </div>
							              <div class="col-md-6 col-sm-6">
							              	<div class="row">
							                    <div class="col-lg-12 col-md-12">
							                        <div class="section-title-two">
							                            <h3><span class="icon icon-Pointer"></span> <?php echo $tr->translate("LOCATION");?></h3>
							                        </div>
							                    </div>
							                </div>
						                 <!-- Google Map Start -->
									        <div class="google-map-area">
									            <!--  Map Section -->
									            <?php if (!empty($contact['map'])){
														echo $contact['map'];
												 }else{?>
													<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3991901.8873551!2d102.73614393157487!3d12.292761097008988!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x310787bfd4dc3743%3A0xe4b7bfe089f41253!2sCambodia!5e0!3m2!1sen!2skh!4v1494389183880" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
												<?php }?>
									        </div>
								        <!-- Google Map End -->
						        		 </div>
						            </div>
						        </div>
						        <!-- Contact Form Area End -->
						     <?php }else if ($menu_info['menu_type_id']==5){//faq
												 $faq = $db->getAllFaq();
												 ?>  
						     <div class="sigle_article">
							    <div class="fix-bg">
								    <div class="img" style="background-image:url('<?php echo $this->baseUrl()."/images/singlebg.jpg"?>');"></div>
								    <div class="inside">
									</div>
							 	 </div>
							 	  <div class="container siglearticle" >
								     <!-- Breadcrumb Area Start-->
										<div class="breadcrumb-area bg-9">	
											<div class="container">
												<div class="row">
													<div class="col-md-4">
														<div class="breadcrumb-text text-left">
															<h2><?php echo $menu_info['title_menu'];?></h2>
															<div class="breadcrumb-bar">
																<ul class="breadcrumb">
																	<li><a href="<?php echo $this->baseUrl();?>"><?php echo $tr->translate("HOME");?></a></li>
																	<li><?php echo $menu_info['title_menu'];?></li>
																</ul>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<!-- Breadcrumb Area End -->
										<!-- Blog Section Area Start -->
								        <div class="blog-section-area ptb-20">
								            <div class="">
								                <div class="row">
									                <div class="col-md-2 col-sm-12 col-xs-12">
									                </div>
									                 <!-- cd-faq-items -->
								               		 <div class="cd-faq-items  col-md-8 col-sm-12 col-xs-12">
								               		 <?php if (!empty($faq)) foreach ($faq as $rs){?>
								               		 	<button class="accordion"><?php echo $rs['title'];?></button>
														<div class="panel">
														  <p><?php echo $rs['description'];?></p>
														</div>
														<?php }?>
														
													</div> <!-- cd-faq-items -->
													<div class="col-md-2 col-sm-12 col-xs-12">
								                	</div>
								                </div>
							                </div>
							            </div>
							            <!-- Blog Section Area End -->
							          </div>
					          </div>
					            <script>
								var acc = document.getElementsByClassName("accordion");
								var i;
								
								for (i = 0; i < acc.length; i++) {
								  acc[i].onclick = function() {
								    this.classList.toggle("active");
								    var panel = this.nextElementSibling;
								    panel.classList.toggle("active");
								    if (panel.style.maxHeight){
								      panel.style.maxHeight = null;
								    } else {
								      panel.style.maxHeight = panel.scrollHeight + "px";
								    } 
								  }
								}
								</script>
							<?php }?>
	<?Php }else if(!empty($this->param['article'])){ 
	$aticle = $this->article_de;
	$lastestart = $db->getArcticleByCateLastesArticle($aticle['category_id'],$aticle['id']);
	$cateinfo = $db->getCategoryByID($aticle['category_id']);
	?>	
	<title><?php echo $aticle['title'];?></title>
	<!-- Breadcrumb Area Start-->
			<div class="breadcrumb-area siglearticle bg-8">	
				<div class="container">
					<div class="row">
						<div class="col-md-8">
							<div class="breadcrumb-text text-left">
								<h2><?php echo $cateinfo['title'];?></h2>
								<div class="breadcrumb-bar">
								<?php if (!empty($cateinfo['sub_title'])){?>
								<p class="subtitle"><?php echo $cateinfo['sub_title'];?></p>
								<?php }else{?>
									<ul class="breadcrumb">
										<li><a href="<?php echo $this->baseUrl();?>"><?php echo $tr->translate("HOME");?></a></li>
										<li><?php echo $cateinfo['title'];?></li>
									</ul>
								<?php }?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Breadcrumb Area End -->
		<div class="sigle_article ">
	 	 <div class="container siglearticle" >
	        <!-- Blog Section Area Start -->
	        <div class="blog-section-area ptb-50">
	            <div class="container">
	                <div class="row">
	                     <div class="col-md-8 col-sm-12 col-xs-12">
	                        <div class="single-blog-post blog-details">
	                            
	                            <div class="blog-post-text">
	                                <h4><?php echo $aticle['title'];?></h4>
	                                <!-- <div class="blog-post-meta">
		                                <span><i class="fa fa-calendar"></i> <span><?php //echo date("d-M-Y",strtotime($aticle['create_date']));?></span></span>
		                            </div>-->
	                               <div class="article_desc">
	                               <?php echo $aticle['description'];?>
	                               </div>
	                            </div>
	                        </div>
	                    </div>
	                     <div class="col-md-4 col-sm-12 col-xs-12">
	                    <?php if (!empty($lastestart)){?>
	                        <div class="ht-single-widget right_blog">
	                            <h4 class="widget-title"><?php echo empty($aticle['cate_title'])?$tr->translate("LASTEST_ARTICLE"):$aticle['cate_title'].$tr->translate("NEW");?></h4>
	                            <div class="ht-widget-item">
	                                <div class="widget-content">
	                                <?php foreach ($lastestart as $rs){?>
	                                    <div class="popular-post">
	                                        <a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"; ?>">
	                                        <?php if(!empty($rs['image_feature'])){?>
												<img src="<?php echo $this->baseUrl()."/images/article/".$rs['image_feature'];?>" />
											<?php }else{?>
												<img src="<?php echo $this->baseUrl()."/images/noimage.jpg";?>"/>
											<?php }?>
	                                        </a>
	                                        <div class="post-text">
	                                            <h6><a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"; ?>"><?php echo $rs['title'];?></a></h6>
	                                        </div>
	                                    </div>
	                                    <?php }?>
	                                    <div class="blog-advertise">
											<?php foreach ($banner as $rs){?>
											<div class="row_advertise pb-20"> 
												<img src="<?php echo $this->baseUrl()."/images/banner/".$rs;?>" class="ad_img" />
											</div>
											<?php }?>
										</div>
	                                </div>
	                            </div>
	                        </div>
	                    <?php }?>
	                     </div>
	                </div>
	            </div>
	        </div>
	        <!-- Blog Section Area End -->
	       </div>
	      </div>
	  </div>
	<?Php }else if(!empty($this->param['category'])){  
	
		$article = $db->getArcticleByCateForlistAll($this->cate['id']);
		$countarticle = $db->countarticle($menu_info['category_id']);
			
		$limits = $db->getWebsiteSetting("items_per_page");
		$paginator = Zend_Paginator::factory($article);
		$paginator->setDefaultItemCountPerPage($limits['value']);
		$allItems = $paginator->getTotalItemCount();
		$countPages= $paginator->count();
		$p = Zend_Controller_Front::getInstance()->getRequest()->getParam('pages');
		
		if(isset($p))
		{
			$paginator->setCurrentPageNumber($p);
		} else $paginator->setCurrentPageNumber(1);
			
		$currentPage = $paginator->getCurrentPageNumber();
		
		$articless  = $paginator;
		if($currentPage == $countPages)
		{
			$nextPage = $countPages;
			$previousPage = $currentPage-1;
		}
		else if($currentPage == 1)
		{
			$nextPage = $currentPage+1;
			$previousPage = 1;
		}
		else {
			$nextPage = $currentPage+1;
			$previousPage = $currentPage-1;
		}
		?>
	<title><?php echo $this->cate['title'];?></title>
	<!-- Breadcrumb Area Start-->
	<div class="breadcrumb-area bg-8">	
		<div class="container">
			<div class="row">
				<div class="col-md-8">
					<div class="breadcrumb-text text-left">
						<h2><?php echo $this->cate['title'];?></h2>
						<div class="breadcrumb-bar">
						<?php if (!empty($this->cate['sub_title'])){?>
							<p class="subtitle"><?php echo $this->cate['sub_title'];?></p>
						<?php }else{?>
							<ul class="breadcrumb">
								<li><a href="<?php echo $this->baseUrl();?>"><?php echo $tr->translate("HOME");?></a></li>
								<li><?php echo $this->cate['sub_title'];?></li>
							</ul>
						<?php }?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcrumb Area End -->
	<!-- Blog Section Area Start -->
        <div class="blog-section-area ptb-50">
            <div class="container">
                <div class="row">
                   <div class="col-md-8 col-sm-12 col-xs-12">
                        <div class="single-blog-post-wrapper">
                        <?php if(!empty($articless)) foreach($articless as $article){ ?>
                            <div class="single-blog-post col-md-6 col-sm-12 col-xs-12">
                            	<div class="list">
	                                <div class="blog-image">
	                                    <a href="<?php echo $this->baseUrl()."/page/index?article=".$article['alias_article'].".html"; ?>">
                                    <?php if(!empty($article['image_feature'])){?>
										<img src="<?php echo $this->baseUrl()."/images/article/".$article['image_feature'];?>"/>
									<?php }else{?>
										<img src="<?php echo $this->baseUrl()."/images/noimage.jpg";?>"/>
									<?php }?>
                                    </a>
                                </div>
                                <div class="blog-post-text">
                                    <h4><a href="<?php echo $this->baseUrl()."/page/index?article=".$article['alias_article'].".html"; ?>"><?php echo $article['title'];?></a></h4>
                                   <!-- <div class="blog-post-meta">
	                                    <span><i class="fa fa-calendar"></i> <span><?php //echo date("d-M-Y",strtotime($article['create_date']));?></span></span>
	                                </div> -->  
                                    <p>
	                                    <?php
											echo mb_substr($article['description'],0,100, "utf-8")."...";
										?> 
										</p>
									<div class="readmore">
                                    <a href="<?php echo $this->baseUrl()."/page/index?article=".$article['alias_article'].".html"; ?>" class="default-btn"><span><?php echo $tr->translate("READ_MORE")?></span></a>
	                               		</div>
	                                </div>
                                </div>
                            </div>
                            <?php }?>
                        </div>
                        <?php 
                        if($countPages>1){ 
						 	$statpage = $currentPage - 5;
						 	$endpage = $currentPage + 5;
						 	if ($currentPage<=5){
						 		$statpage = 1;
						 		$endpage =10;
						 	}
                        }
                        if (!empty($countPages)){
						 ?> 
                        <div class="col-md-12 col-sm-12 col-xs-12 pagination-wrapper fix">
                            <div class="pagination-content">
                            <?php if($countPages>1){ ?>
                                <ul class="pagination">
	                                 <li class="<?php if($currentPage==1){ echo "active";}?>">
                               	  	<a href="<?php echo $this->baseUrl()."/page/index?param=".$this->param['param']."&pages=".$previousPage;?>"><i class="fa fa-angle-left"></i></a>
	                                 </li>
                                    <?php  $i=0; for( $i=1; $i<=$countPages; $i++){?>
		           			 	<?php if ($statpage<=$i && $endpage>=$i){?>
                                   					 <li class="<?php if($i==$currentPage){ echo "active";}?>">
                                   					 	<a href="<?php echo $this->baseUrl()."/page/index?param=".$this->param['param']."&pages=".$i;?>"><?php echo $i;?></a>
                                   					 </li>
                                                 <?php }}?>
                                                 <li class="<?php if($countPages==$currentPage){ echo "active"; }?>">
                               	  	<a "href="<?php echo $this->baseUrl()."/page/index?param=".$this->param['param']."&pages=".$nextPage;?>"><i class="fa fa-angle-right"></i></a>
	                                 </li>
                                </ul>
                           		<?php }?>
                            </div>
                        </div>
                        <?php }?>
                    </div>
                    <div class="col-md-4 col-sm-12 col-xs-12">
                 	   <?php if (!empty($banner)){?>
					<div class="blog-advertise">
						<?php foreach ($banner as $rs){?>
						<div class="row_advertise pb-20"> 
							<img src="<?php echo $this->baseUrl()."/images/banner/".$rs;?>" class="ad_img" />
						</div>
						<?php }?>
					</div>
					<?php }?>
					</div>
                </div>
            </div>
        </div>
        <!-- Blog Section Area End -->
	<?Php }?>