<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$dbselect = new Application_Model_DbTable_DbGlobalSelect();
$session_lang=new Zend_Session_Namespace('lang');
$currentlang = $session_lang->lang_id;
if ($currentlang==1){
	$day = array("Mon"=>"Monday", "Tue"=>"Tuesday", "Wed"=>"Wednesday","Thu"=>"Thursday", "Fri"=>"Friday", "Sat"=>"Saturday", "Sun"=>"Sunday");
	$number = array("0","1","2","3","4","5","6","7","8","9");
	$month = array("01"=>"Jan", "02"=>"Feb", "03"=>"Mar","04"=>"Apr", "05"=>"May", "06"=>"Jun", "07"=>"Jul","08"=>"Aug", "09"=>"September", "10"=>"Oct","11"=>"Nov", "12"=>"Dec");
}else{
	$day = array("Mon"=>"ថ្ងៃច័ន្ទ", "Tue"=>"ថ្ងៃអង្គារ", "Wed"=>"ថ្ងៃពុធ","Thu"=>"ថ្ងៃព្រហស្បត្តិ៍", "Fri"=>"ថ្ងៃសុក្រ", "Sat"=>"ថ្ងៃសៅរ៍", "Sun"=>"ថ្ងៃអាទិត្យ");
	$number = array("០","១","២","៣","៤","៥","៦","៧","៨","៩");
	$month = array("01"=>"មករា", "02"=>"កុម្ភៈ", "03"=>"មិនា", "04"=>"មេសា", "05"=>"ឧសភា", "06"=>"មិថុនា", "07"=>"កក្កដា","08"=>"សីហា", "09"=>"កញ្ញា", "10"=>"តុលា","11"=>"វិច្ឆិការ", "12"=>"ធ្នូ");
}
?>
 	<title><?php echo $tr->translate("COMPANY_NAME");?></title>
		<!-- Slider Three Area Start -->
		<div class="slider-three-area">
		    <div class="slider-wrapper">
		    <?php if(!empty($this->slideshow))  foreach($this->slideshow as $key => $ss){?>
		        <div  data-dot="<?php echo $key+1;?>" class="single-slide" style="background-image: url('<?php echo $this->baseUrl()."/images/slide/".$ss; ?>');">
                    <div class="banner-content">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-7 col-md-10 col-sm-12 col-xs-12">
                                
                                </div>
                            </div>
                        </div>
                    </div>
		        </div>
		         <?php }?> 
		    </div>
		</div>
		<!-- Slider Three Area End -->
		 <div class="blog-two-area messageblog ptb-20">
              <div class="container">
            	<h2 class="hotnews">
            		<?php echo $this->rsmessage['description'];?>
            	</h2>
            </div>
         </div>
		<?php if (!empty($this->gethomearticle)){?>
		<!-- Blog Two Area Start -->
        <div class="blog-two-area newsevent ptb-20">
            <div class="container">
           
                <div class="section-title-light text-center fix">
                    <h2><?php echo $this->categoryinfo['title'];?></h2>
                </div>
                <div class="row">
                    <div class="blog-carousel">
                        <?php foreach ($this->gethomearticle as $rs){
                        	?>
						<div class="col-xs-12">
                            <div class="single-blog listnews">
                                <div class="blog-image">
                                    <a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"?>">
                                    	<?php if (!empty($rs['image_feature'])){?>
                                      	  <img src="<?php echo $this->baseUrl()."/images/article/".$rs['image_feature']?>" alt="">
                                        <?php }else{?>
                                       	  <img src="<?php echo $this->baseUrl()."/images/noimage.jpg"?>" alt="">
                                        <?php }?>
                                    </a>
                                </div>
                                <div class="blog-text">
                                    <h5><a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"?>"><?php echo mb_substr($rs['title'],0,120, "utf-8");?></a></h5>
                                    <p><?php
                                    	echo mb_substr($rs['description_forweb'],0,100, "utf-8")."...";
                                    ?></p>
                                    <div class="readmore">
										<a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"?>" class="default-btn readmore"><span><?php echo $tr->translate("READ_MORE");?></span></a>
									</div>
                                </div>
                            </div>
                        </div>
                        <?php }?>
                     </div>
                </div>
				<div class="section-button text-center pt-20">
					<a href="<?php echo $this->baseUrl()."/page/index?category=".$this->categoryinfo['alias_category'].".html";?>" class="default-btn showall"><span><?php echo $tr->translate("SHOW_ALL");?></span></a>
				</div>
             </div>
         </div>
        <!-- Blog Two Area End -->
        <?php }?>
        <?php if (!empty($this->getAllDepart)){?>
        <!-- Tap Area Start -->
        <div class="tap-area  pb-20">
		   <div class="tapfeature"><!--menu-->
				<div class="container">
					<ul class="menutap">
						<?php foreach ($this->getAllDepart as $key => $dep){?>
						<li <?php if ($key==0){?>class="active"<?php }?>>
							<a href="<?php echo "#dept".$key;?>" data-toggle="tab" aria-expanded="true">
								<span class="middle"><?php echo $dep['title'];?></span>
							</a>
						</li>
						<?php }?>
					</ul>
				</div>
			</div>
			<div class="container">
				<div class="nav-tab-content tab-content">
				<?php foreach ($this->getAllDepart as $key => $dep){?>
					<div id="<?php echo "dept".$key;?>" class="tab-pane postlist fade list-article <?php if ($key==0){?>active in<?php }?>" data-role="content">
						<?php $company = $dbselect->getCompanyByDept($dep['id']);?>
						<div class="content-tap">
						<?php $list=5; $limt=$list; $i=0; foreach ($company as $com){ $i++;?>
						<?php if ($i==1){?>
							<ul class="list_compay col-md-4 col-sm-4 col-xs-12">
							<?php }?>
								<li><a href="<?php echo $this->baseUrl()."/searchcompany?company=".base64_encode($com['id']);?>"><?php echo $com['com_name'];?></a></li>
							<?php if (count($company)==$i){?>
							</ul>
							<?php }else if ($i==$limt){ $limt = $limt+$list;?>
							</ul>
							<ul class="list_compay col-md-4 col-sm-4 col-xs-12">
							<?php }?>
							
							
						<?php }?>
							
						</div>
					
					</div>
				<?php }?>
				</div>
			</div>
        </div>
        <!-- Tap Area End -->
        <?php }?>
       <div class="blog-two-area ptb-20">
			<a href="#"><img src="<?php echo $this->baseUrl()."/template/"?>home.jpg" alt=""></a>
	   </div>
	   <?php if (!empty($this->document)){?>
        <!-- Blog Two Area Start -->
        <div class="file_slide ptb-20">
            <div class="container">
                <div class="row">
                    <div class="blog-file-slide">
                    <?php foreach ($this->document as $doc){
                    	if (!empty($doc['image'])){
                    	$image = $this->baseUrl()."/companylogo/".$doc['image'];
                    	}else{
                    		$image = $this->baseUrl()."/template/file.jpg";
                    	}
                    	?>
                        <div class="col-xs-12">
                            <div class="single-blog">
								<div class="title_date">
									<!-- ថ្ងៃច័ន្ទ ២១ មេសា ២០១៧ -->
									<?php 
									$date = strtotime($doc['modify_date']);
									$spp = str_split(date("d",$date));
									$num="";
									foreach ($spp as $ss){
										$num.=$number[$ss];
									}
									$year='';
									$sp_year = str_split(date("Y",$date));
									foreach ($sp_year as $y){
										$year.=$number[$y];
									}
									echo $day[date("D",$date)]." ".$num." ".$month[date("m",$date)]." ".$year;?>
								</div>
                                <div class="blog-image">
                                    <a href="<?php echo $this->baseUrl()."/file/".$doc['file_name'];?>" target="_blank" download title="<?php echo $doc['title'];?>">
                                        <img src="<?php echo $image;?>" alt="">
                                    </a>
                                </div>
                               
                            </div>
                        </div>
                        <?php }?>
                    </div>
					<div class="section-button text-center pt-20">
						<a href="<?php echo $this->baseUrl()."/documents";?>" class="default-btn showall"><span><?php echo $tr->translate("SHOW_ALL");?></span></a>
					</div>
                </div>
            </div>
        </div>
        <!-- Blog Two Area End -->
        <?php }?>
		
		<div class="blog-two-area ptb-20">
			<a href="#"><img src="<?php echo $this->baseUrl()."/template/"?>formheader.jpg" alt=""></a>
	   </div>  
		<div class="blog-two-area ptb-20">
			<div class="container">
                 <div class="row">
				 <div class="col-md-2 col-sm-12 col-xs-12">
				 </div>
					<div class="col-md-8 col-sm-12 col-xs-12">
						<form action="<?php echo $this->baseUrl()."/searchcompany";?>" method="GET">
							<div class="form_search_home">
								<div class="row-form-home">
									<div class="label_title"><?php echo $tr->translate("Zip Code");?></div>
									<div class="field_value" >
										<input type="text" name="zip_code" id="zip_code" placeholder="<?php echo $tr->translate("Zip Code");?>">
									</div>
								</div>
								<div class="row-form-home">
									<div class="label_title"><?php echo $tr->translate("Organize_under");?></div>
									<div class="field_value" >
										<select name="oranization" id="oranization" class="js-select2" >
											<option value="-1"><?php echo $tr->translate("CHOOSE_Organize_under");?></option>
											<?php if(!empty($this->rsdepartment)){
										foreach($this->rsdepartment as $rs){
									?>	
										<option value="<?php echo $rs['id'];?>"><?php echo $rs['name'];?></option>
										<?php }}?>
										</select>
									</div>
								</div>
								<div class="row-form-home">
									<div class="label_title"><?php echo $tr->translate("PRODUCT");?></div>
									<div class="field_value" >
										<input type="text" name="product" id="product" placeholder="<?php echo $tr->translate("PLEASE_ENTER_PRODUCT_OF_OGR");?>">
									</div>
								</div>
								<div class="row-form-home">
									<div class="label_title"><?php echo $tr->translate("City_Province");?></div>
									<div class="field_value" >
										<select name="province" id="province" class="js-select2" >
											<option value="-1"><?php echo $tr->translate("Choose_City_Province");?></option>
											<?php if(!empty($this->rsprovince)){
													foreach($this->rsprovince as $rs){
											?>	
													<option <?php if($this->rssearch['province_id']==$rs['id']){echo "selected";}?> value="<?php echo $rs['id'];?>"><?php echo $rs['name'];?></option>
											<?php }}?>
										</select>
									</div>
								</div>
								<div class="row-form-home">
									<div class="button_submit" >
										<input type="submit" value="<?php echo $tr->translate("SEARCH_ORG");?>"  class="btu_submit"/>
									</div>
								</div>
							</div>
						</form>
					</div>
					<div class="col-md-2 col-sm-12 col-xs-12">
				 </div>
				 </div>
			</div>
		</div>
		<?php if (!empty($this->partner)){?>
		<div class="partner ptb-20">
			<div class="container">
				 <div class="section-title-light text-center fix">
                    <h2><?php echo $tr->translate("PARTNER");?></h2>
                </div>
				<div class="row">
					<div class="partner_list_content">
						<ul class="partner_list">
						<?php foreach ($this->partner as $rs){?>
							<li class="col-md-2 col-sm-3 col-xs-6 partnerlist"><img src="<?php echo $this->baseUrl()."/images/slide/partner/".$rs?>" /><li>
						<?php }?>
						</ul>
					</div>
				 </div>
			 </div>
	   </div>  
	   <?php }?>
 