<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("DEPARTMENT_LIST"));
$frm = $this->frm;
$frms = $this->frm_search;
$url_delete ="";//$this->url(array('module'=>'menu-manager','controller'=>'category','action'=>'delete'));
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
 <form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
   <table width="70%">
   <tr>
		<td><input placeHolder="កូដ ឈ្មោះ ទូរសព្ទ ផលិតផល" value="<?php echo $this->rssearch['txt_search'];?>" dojoType="dijit.form.TextBox" class="fullside" name="txt_search" id="txt_search" type="text"><td>
		<td>
			<select class="fullside" dojoType="dijit.form.FilteringSelect" name="department" id="department">
				<option value="-1">ជ្រើសរើស ស្ថាប័នក្រោមចំនុះ</option>
				<?php if(!empty($this->rsdepartment)){
						foreach($this->rsdepartment as $rs){
				?>	
						<option <?php if($this->rssearch['department']==$rs['id']){echo "selected";}?> value="<?php echo $rs['id'];?>"><?php echo $rs['name'];?></option>
				<?php }}?>
			</select>
		<td>
		<td><select class="fullside" name="province_id" id="province_id" dojoType="dijit.form.FilteringSelect">
				<option value="-1">ជ្រើសរើស រាជធានី/ខេត្ត</option>
				<?php if(!empty($this->rsprovince)){
						foreach($this->rsprovince as $rs){
				?>	
						<option <?php if($this->rssearch['province_id']==$rs['id']){echo "selected";}?> value="<?php echo $rs['id'];?>"><?php echo $rs['name'];?></option>
				<?php }}?>
			</select>
		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
   		</td>
   </tr>
</table>
</form>
<?php echo $this->list;?>
<script type="text/javascript">
dojo.require("dijit.form.CheckBox"); 
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.Dialog");
	var recordid ='';
	function  resetForm(){
		var datenow = '<?php echo date("Y-m-d");?>';
		dijit.byId('adv_search').attr('value','');
		dijit.byId('status_search').set('value','-1');
	}
	function deleteRecord(url){
		 id = recordid;
		 window.location.href = url+'/id/'+id;
	}
	function showDeleteForm(id){
		if(id==''){
			alert("No record selected for delete.");
			dijit.byId('deleteForm').hide();
		}else{
			dijit.byId('deleteForm').show();
			recordid = id;
		}
	}
	function closeForm(){
		dijit.byId('deleteForm').hide();
	}
</script> 
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'តើអ្នកពិតជាលុបទិន្នន័យនេះមែនទេ?'"  id="deleteForm" style="width:350px;" >
		<div style=" text-align: center;">
			<h4>តើអ្នកពិតជាលុបទិន្នន័យនេះមែនទេ?</h4>
			<button onclick="deleteRecord('<?php echo $url_delete;?>')" iconclass="dijitIconDelete" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("DELETE");?></button>
			<button onclick="closeForm();" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("CANCEL");?></button>
		</div>
	</div>
</div>