<?php 
$url="http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$session_lang=new Zend_Session_Namespace('lang');
$currentlang = $session_lang->lang_id;
if ($currentlang==1){
	$day = array("Mon"=>"Monday", "Tue"=>"Tuesday", "Wed"=>"Wednesday","Thu"=>"Thursday", "Fri"=>"Friday", "Sat"=>"Saturday", "Sun"=>"Sunday");
	$number = array("0","1","2","3","4","5","6","7","8","9");
	$month = array("01"=>"Jan", "02"=>"Feb", "03"=>"Mar","04"=>"Apr", "05"=>"May", "06"=>"Jun", "07"=>"Jul","08"=>"Aug", "09"=>"September", "10"=>"Oct","11"=>"Nov", "12"=>"Dec");
}else{
	$day = array("Mon"=>"ថ្ងៃច័ន្ទ", "Tue"=>"ថ្ងៃអង្គារ", "Wed"=>"ថ្ងៃពុធ","Thu"=>"ថ្ងៃព្រហស្បត្តិ៍", "Fri"=>"ថ្ងៃសុក្រ", "Sat"=>"ថ្ងៃសៅរ៍", "Sun"=>"ថ្ងៃអាទិត្យ");
	$number = array("០","១","២","៣","៤","៥","៦","៧","៨","៩");
	$month = array("01"=>"មករា", "02"=>"កុម្ភៈ", "03"=>"មិនា", "04"=>"មេសា", "05"=>"ឧសភា", "06"=>"មិថុនា", "07"=>"កក្កដា","08"=>"សីហា", "09"=>"កញ្ញា", "10"=>"តុលា","11"=>"វិច្ឆិកា", "12"=>"ធ្នូ");
}
?>
<title><?php echo $tr->translate("EYES_OF_PUBLIC");?></title>
		<!-- Breadcrumb Area Start-->
		<div class="breadcrumb-area bg-8">	
			<div class="container">
				<div class="row">
					<div class="col-md-8">
						<div class="breadcrumb-text text-left">
							<h2><?php echo $tr->translate("EYES_OF_PUBLIC");?></h2>
							<div class="breadcrumb-bar">
								<p class="subtitle"><?php echo $tr->translate("Strengthen effective work and show people what we have done");?></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Breadcrumb Area End -->
		<div class="blog-two-area ptb-20">
			<div class="container">
                 <div class="row">
					<div class="col-md-8 col-sm-12 col-xs-12">
						<ul class="result-list eyepublic">
							<?php foreach ($this->document as $document){?>
							<li class="col-md-4 col-sm-4 col-xs-12 pb-20">
								<div class="post_date text-center">
										<span class="date ">
										<?php 
										$date = strtotime($document['modify_date']);
										$spp = str_split(date("d",$date));
										$num="";
										foreach ($spp as $ss){
											$num.=$number[$ss];
										}
										$year='';
										$sp_year = str_split(date("Y",$date));
										foreach ($sp_year as $y){
											$year.=$number[$y];
										}
										echo $day[date("D",$date)]." ".$num." ".$month[date("m",$date)]." ".$year;
										?>
										</span>
									</div>
								<div class="image_blog">
									<?php 
									$image = $this->baseUrl()."/images/noimage.jpg";
									if (!empty($document['image'])){
											$image = $this->baseUrl()."/companylogo/".$document['image'];
										}
									?>
									<a target="_blank" href="<?php echo $this->baseUrl()."/file/".$document['file_name'];?>">
									<img src="<?php echo $image;?>" />
									</a>
								</div>
								<div class="clearboth"></div>
							</li>
							<?php }?>
							</ul>
							
							<?php 
	                        if($this->countPages>1){ 
							 	$statpage = $this->currentPage - 5;
							 	$endpage = $this->currentPage + 5;
							 	if ($this->currentPage<=5){
							 		$statpage = 1;
							 		$endpage =10;
							 	}
	                        }
	                        if (!empty($this->countPages)){
							 ?> 
	                        <div class="col-md-12 col-sm-12 col-xs-12 pagination-wrapper fix">
	                            <div class="pagination-content">
	                            <?php if($this->countPages>1){ ?>
	                                <ul class="pagination">
		                                 <li class="<?php if($this->currentPage==1){ echo "active";}?>">
		                               	  	<a href="<?php echo $url."&pages=".$this->previousPage;?>"><i class="fa fa-angle-left"></i></a>
		                                 </li>
	                                    <?php  $i=0; for( $i=1; $i<=$this->countPages; $i++){?>
				           			 	<?php if ($statpage<=$i && $endpage>=$i){?>
                                   					 <li class="<?php if($i==$this->currentPage){ echo "active";}?>">
                                   					 	<a href="<?php echo $url."&pages=".$i;?>"><?php echo $i;?></a>
                                   					 </li>
                                                 <?php }}?>
                                                 <li class="<?php if($this->countPages==$this->currentPage){ echo "active"; }?>">
		                               	  	<a "href="<?php echo $url."&pages=".$this->nextPage;?>"><i class="fa fa-angle-right"></i></a>
		                                 </li>
	                                </ul>
	                           		<?php }?>
	                            </div>
	                        </div>
	                        <?php }?>
					</div>
					<div class="col-md-4 col-sm-12 col-xs-12">
				<?php if (!empty($this->banner)){?>
						<div class="blog-advertise" style="margin-top:30px;">
							<?php foreach ($this->banner as $rs){?>
							<div class="row_advertise pb-20"> 
								<?php if($rs['option_link']==1){ echo '<a href="'.$this->baseUrl().'/banner/index/ads/'.base64_encode($rs['id']).'">'; }else{ echo '<a href="'.$rs['link'].'" target="_blank">'; } ?><img style="width:100%" src="<?php echo $this->baseUrl()."/images/banner/".$rs['image']?>" /></a>
							</div>
							<?php }?>
						</div>
				<?php }?>
		 			</div>
				 </div>
			</div>
		</div>