<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_COMPANY'));
	$rsdata = $this->rs;
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
dojo.require("dijit.layout.TabContainer");
dojo.require("dijit.form.Textarea");
</script>
<style>

</style>
<form id='company' action="" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:-5px;">
	<tr class="header">
		<td colspan="2"><strong><i class="fa fa-users" aria-hidden="true"></i><?php echo $tr->translate('EDIT_COMPANY')?></strong></td>
	</tr>
	<tr>
		<td style="max-width:1100px;border: solid 1px #eee;background: rgba(241, 241, 241, 0.2);">
		<table style="margin: 0 auto; width: 100%;">
			<tr>
				<td align="left" valign="top">
						<table style="margin: 0 auto; width: 100%;" cellspacing="10">
							<tr>
								<td><?php echo $tr->translate("លេខកូដ")?></td>
								<td><input dojoType="dijit.form.TextBox" value="<?php echo $rsdata['com_code']?>" class="fullside" name="company_code" id="company_code" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ឈ្មោះក្រុមហ៊ុន")?></td>
								<td><input dojoType="dijit.form.ValidationTextBox" value="<?php echo $rsdata['com_name']?>" required="1" class="fullside" name="company_name" id="company_name" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("លេខទូរសព្ទ")?></td>
								<td><input dojoType="dijit.form.TextBox" value="<?php echo $rsdata['com_phone']?>" class="fullside" name="phone" id="phone" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("អាស័យដ្ឋាន")?></td>
								<td><input dojoType="dijit.form.TextBox" value="<?php echo $rsdata['address']?>" class="fullside" name="address" id="address" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ថ្ងៃចុះបញ្ជី")?></td>
								<td><input dojoType="dijit.form.DateTextBox" value="<?php echo $rsdata['register_date']?>" constraints="{datePattern:'dd/MM/yyyy'}" class="fullside" name="date_register" id="date_register"  type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ស្ថាប័នក្រោមចំនុះ")?></td>
								<td>
									<select class="fullside" dojoType="dijit.form.FilteringSelect" name="department" id="department">
										<?php if(!empty($this->rsdepartment)){
												foreach($this->rsdepartment as $rs){
										?>	
												<option <?php if($rsdata['depart_id']==$rs['id']){echo "selected";}?> value="<?php echo $rs['id'];?>"><?php echo $rs['name'];?></option>
										<?php }}?>
									</select>
								</td>
							</tr>
							<tr>
								<td colspan="2" align="right">
									<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" iconClass="dijitIconClear" /> 
									<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('EDIT');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
										iconClass="dijitEditorIcon dijitEditorIconSave" />
								</td>
							</tr>
						</table>
					</td>
					<td width="50%" style="background:#eaeaea;">
						<table style="margin: 0 auto; width: 100%;" cellspacing="10">
							<tr>
								<td><?php echo $tr->translate("ផលិតផល")?></td>
								<td><input dojoType="dijit.form.TextBox" value="<?php echo $rsdata['product']?>" class="fullside" name="product_name" id="product_name" type="text"></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("រាជធានី/ខេត្ត")?></td>
								<td>
									<select class="fullside" name="province_id" id="province_id" dojoType="dijit.form.FilteringSelect">
										<?php if(!empty($this->rsprovince)){
												foreach($this->rsprovince as $rs){
										?>	
												<option <?php if($rsdata['province_id']==$rs['id']){echo "selected";}?> value="<?php echo $rs['id'];?>"><?php echo $rs['province_kh_name'];?></option>
										<?php }}?>
									</select>
								</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("អំពីក្រុមហ៊ុន")?></td>
								<td><input dojoType="dijit.form.TextBox" value="<?php echo $rsdata['note']?>" class="fullside" name="note" id="note" type="text"></td>
							</tr>
							<tr>
								<td valign="top"><?php echo $tr->translate("ឡូហ្គូក្រុមហ៊ុន/Logo")?> (jpg, .jpeg, .png</td>
								<td valign="top">
									<input style="width:90px;" class="fullside" required="1" name="logo" id="logo" accept=".jpg, .jpeg, .png" type="file"><img src="<?php echo $this->baseUrl()."/companylogo/".$rsdata['logo'];?>" width="100px"/>
										<input type="hidden" name="old_logo" value="<?php echo $rsdata['logo'];?>" />
									</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ឯកសារច្បាប់")?> (jpg, .jpeg, .png)</td>
								<td><input class="fullside" required="1" name="document_company" accept=".jpg, .jpeg, .png" multiple type="file"></td>
							</tr>
							<tr>
								<td colspan="2" align="center">
								<?php for ($i=1;$i<=8;$i++){ 
								if(!empty($rsdata['file'.$i])){?>
									<img src="<?php echo $this->baseUrl()."/companylogo/".$rsdata['file'.$i];?>" width="60px"/>
								<?php }?>
								<input type="hidden" name="document_company<?php echo $i?>" value="<?php echo $rsdata['file'.$i];?>" />
								<?php }?>
								</td>
							</tr>
					</table>
				</td>
			</tr>
		</table>
			
		</td>
	</tr>
</table>	
</form>
<table>
<tr>
</tr>
</table>
<script type="text/javascript">
var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){	
	dijit.byId("province_id").attr("value",12);
	/*try{
		new dijit.form.FilteringSelect({
		store: district_store,
		autoComplete: true,
		required: false,		           
		name: "district",
		id: "district",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",	
			onChange: function() {
				district = dijit.byId('district').get('value');
				if(district==-1){
					showPopupdistrict();
					}
					filterCommune();
			}  
		}, "district");
		 
		new dijit.form.FilteringSelect({
		store: commune,
		autoComplete: true,
		required: false,		           
		name: "commune",
		id: "commune",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឃុំ/សង្កាត់",	
			onChange: function() {
				commune = dijit.byId('commune').get('value');
				if(commune==-1){
					showPopupCommune();
				}
				else{
					filterVillage();
				}
			  }
		}, "commune");		 

	}catch(e){
		alert(e);
	}*/
});
</script>