<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_DOCUMENT'));
	$rsdata = $this->rs;
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
//dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
//dojo.require("dijit.form.CheckBox");
//dojo.require("dijit.Dialog");
//dojo.require("dijit.layout.TabContainer");
dojo.require("dijit.form.Textarea");
</script>
<style>

</style>
<form id='company' action="" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<table  width="100%" style="margin-top:-5px;">
		<tr class="header">
			<td colspan="2"><strong><i class="fa fa-users" aria-hidden="true"></i><?php echo $tr->translate('EDIT_DOCUMENT')?></strong></td>
		</tr>
		<tr>
			<td style="max-width:1100px;border: solid 1px #eee;background: rgba(241, 241, 241, 0.2);">
			<table style="margin: 0 auto; width: 50%;">
				<tr>
					<td align="left" valign="top">
							<table style="margin: 0 auto; width: 100%;" cellspacing="10">
								<tr>
									<td><?php echo $tr->translate("ឈ្មោះឯកសារ")?></td>
									<td><input dojoType="dijit.form.ValidationTextBox" required="1" class="fullside" name="document_name" id="document_name" value="<?php echo $this->rs['title'];?>" type="text"></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("ឯកសារ")?></td>
									<td>
										<input class="fullside" name="document" id="document" type="file" accept=".jpg, .jpeg, .png, .pdf, .doc, .docx">
										<input class="fullside" name="old_document" id="old_document" type="hidden" value="<?php echo $this->rs['file_name'];?>" >
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("កាលបរិឆ្ឆេទ")?></td>
									<td><input dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" class="fullside" name="date_register" id="date_register" value="<?php echo date("Y-m-d",strtotime($this->rs['create_date']));?>" type="text"></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("ពណ៍នា")?></td>
									<td>
										<textarea class="fullside" name="note" id="note" style="height: 150px;overflow-x:hidden;font-family:'khmer os battambang'; font-size: 14px; "><?php echo $this->rs['description'];?></textarea>
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("ពាក្យគន្លឹះ")?></td>
									<td>
									<input dojoType="dijit.form.TextBox" class="fullside" name="key_word" id="key_word" type="text" value="<?php echo $this->rs['key_word'];?>"></td>
								</tr>
								<tr>
									<td colspan="2" align="center">
										<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" iconClass="dijitIconClear" /> 
										<input type="submit" value="SAVE_CLOSE" tabindex="1" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
											iconClass="dijitEditorIcon dijitEditorIconSave" />
									</td>
								</tr>
							</table>
						</td>
				</tr>
			</table>
			</td>
		</tr>
	</table>
</form>
<table>
<tr>
</tr>
</table>
<script type="text/javascript">
dojo.ready(function(){		
});
</script>