<?php 
$db = new Application_Model_DbTable_DbGlobalSelect();
//$bannerlist = $db->getWebsiteSetting("banner");
//$banner = explode(",", $bannerlist['value']);
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $this->rsfirst['title'];?></title>
	<!-- Breadcrumb Area Start-->
<div class="breadcrumb-area bg-8">	
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<div class="breadcrumb-text text-left">
					<h2><?php echo $tr->translate("DEPARTMENT");?></h2>
					<div class="breadcrumb-bar">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="sigle_article">
 	 <div class="container siglearticle" >
        <!-- Blog Section Area Start -->
        <div class="blog-section-area ptb-20" >
            <div class="container">
                <div class="row">
					<div class="col-md-8 col-sm-12 col-xs-12">
                        <div class="single-blog-post blog-details">
                            <div class="blog-post-text">
                                <h4>
                                	<?php echo $this->rsfirst['title'];?>
                                </h4>
                               <div class="article_desc">
                              		 <?php 
                              		 	echo $this->rsfirst['description'];
                              		?>
                               </div>
                            </div>
                        </div>
                    </div>
					<div class="col-md-4 col-sm-12 col-xs-12">
						<ul class="department">
							<?php if(!empty($this->rsdepartment))foreach($this->rsdepartment as $key =>$rs){?>
							<li <?php if($this->param==$rs['alias'] OR ($this->param=='' AND $key==0)){echo "class='activemenu'";}?>><a href="<?php echo $this->url(array('controller'=>'departments','action'=>'index','dept'=>$rs['alias']));?>"><?php echo $rs['name'];?></a></li>
							<?php }?>
						</ul>
						
						<?php if (!empty($this->banner)){?>
								<div class="blog-advertise" style="margin-top:30px;">
									<?php foreach ($this->banner as $rs){?>
									<div class="row_advertise pb-20"> 
										<?php if($rs['option_link']==1){ echo '<a href="'.$this->baseUrl().'/banner/index/ads/'.base64_encode($rs['id']).'">'; }else{ echo '<a href="'.$rs['link'].'" target="_blank">'; } ?><img style="width:100%" src="<?php echo $this->baseUrl()."/images/banner/".$rs['image']?>" /></a>
									</div>
									<?php }?>
								</div>
						<?php }?>
		 			
					</div>
				</div>
			</div>
		</div>
	</div>
</div>