  <?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  // report
  
  $rpt_client = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-client'));
  
  ?>
  <style>
  ul.link-rpt li a {
	color: #3A3939;
    height: 50px;
  	width:180px;
    display: block;
    padding: 10px;
    background: #D6D6D6;
  	font-family: 'Times New Roman','Kh Battambang','Khmer Battambang' !important;
  	text-align: center;
  	word-wrap: break-word;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  .dijitReset, .dijitInline  ,.dijitButton {
	width: 200px !important;
  }
  </style>
  <div style="background:#ccc; width: 100%;">
  	<ul class="link-rpt">
   	   <?php
   	   $session_user=new Zend_Session_Namespace('auth');
   	   $report_url = $session_user->url_report;
   	   if(!empty($report_url)){
   	   foreach($report_url as $url){?>
   	   <?php if ($url['controller']!="index"){?>
   	   	<li><a href="<?php echo $this->url(array('module'=>$url['module'],'controller'=>$url['controller'],'action'=>$url['action'])); ?>">
   	   	<?php echo $tr->translate($url['label']);?></a></li>
   	   	<?php }?>
   	   <?php }
   	   }?>
  	</ul>
  </div>
  <div style="clear: both;"></div>