<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_CLIENT'));
	
	if(!empty($this->photo)){
		$profile="directory/".$this->photo;
	}else{
		$profile ="profile.jpg";
	}
	$email = $this->row['email'];
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
dojo.require("dijit.layout.TabContainer");
dojo.require("dijit.form.Textarea");
</script>
<style>
.image-box {
    display: inherit;
    position: relative;
    text-align: center;
}
.image-box img {
    width: 150px;
    border-radius: 60%;
    height: 150px;
    margin-top: 10px;
    border: solid 1px #eee;
}
.button_browse {
    margin-top: 10px;
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 38px;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 38px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
}
</style>
<form id='add_client' action="" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(check==1){ alert("Email has been use on other account!");dijit.byId('email').focus(); return false;}
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:-5px;">
	<tr class="header">
		<td colspan="2"><strong><i class="fa fa-users" aria-hidden="true"></i><?php echo $tr->translate('EDIT_CLIENT')?></strong></td>
	</tr>
	<tr>
		<td style="max-width:1100px;border: solid 1px #eee;background: rgba(241, 241, 241, 0.2);">
			<table style="margin: 0 auto; width: 100%;">
				<tr>
					<td align="left" valign="top" width="70%">
						<table style="margin: 0 auto; width: 100%;" cellspacing="10">
							<tr>
								<td><?php echo $tr->translate("USER_NAME")?></td>
								<td><?php echo $frm->getElement('user_name');?></td>
								<td><?php echo $tr->translate("EMAIL")?>
									<span id="error" style=" color: #df0000;"></span>
								</td>
								<td><?php echo $frm->getElement('email');?></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("PASSWORD")?>*</td>
								<td><input dojoType='dijit.form.CheckBox' id="check_change" name="check_change" onChange="Checkchange();" /> <?php  echo $frm->getElement('password');?></td>
								<td><?php echo $tr->translate("PHONE")?>*</td>
								<td><?php  echo $frm->getElement('phone');?></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("COMPANY_NAME")?></td>
								<td><?php  echo $frm->getElement('company_name');?></td>
								<td><?php echo $tr->translate("WEBSITE")?></td>
								<td><?php  echo $frm->getElement('website');?></td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("STATUS")?></td>
								<td><?php echo $frm->getElement('status');?></td>
							</tr>
							<!-- <tr>
								<td><?php //echo $tr->translate("Province")?>*</td>
								<td><?php  //echo $frm->getElement('province');?></td>
								<td><?php //echo $tr->translate("District")?></td>
								<td><input id="district" /></td>
							</tr>
							<tr>
								<td><?php //echo $tr->translate("Commune")?></td>
								<td><input id="commune" /></td>
							</tr> -->
							<tr>
								<td colspan="4" style="border-bottom: solid 1px #ccc;"><?php echo $tr->translate("ADDRESS")?></td>
							</tr>
							<tr>
								<td colspan="4"><?php  	echo $frm->getElement('address');?></td>
							</tr>
							<tr>
								<td colspan="4" align="center">
									<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" iconClass="dijitIconClear" /> 
									<input type="submit" value="SAVE_CLOSE" tabindex="2" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
										iconClass="dijitEditorIcon dijitEditorIconSave" /> 
									<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
										iconClass="dijitEditorIcon dijitEditorIconSave" />
								</td>
							</tr>
						</table>
					</td>
					<td width="10%" style="  vertical-align: top;" >
						<table>
							<tr>
								<td rowspan="4">
									<div class="account-image">
										<div class="image-box">
											<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/'.$profile;?>" alt=""  />
										</div>
										<div class="button_browse">
										<div id='preview'></div>	
												<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
												<input class="btn_borwse_image" type="file" id="profile" name="profile"  onchange="loadFile(event)"/>
										</div>
									</div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>	
</form>
<table>
<tr>
</tr>
</table>
<script type="text/javascript">
var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
/*dojo.ready(function(){
	
	try{
		new dijit.form.FilteringSelect({
		store: district_store,
		autoComplete: true,
		required: false,		           
		name: "district",
		id: "district",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",	
			onChange: function() {
				district = dijit.byId('district').get('value');
				if(district==-1){
					showPopupdistrict();
					}
					filterCommune();
			}  
		}, "district");
		 
		new dijit.form.FilteringSelect({
		store: commune,
		autoComplete: true,
		required: false,		           
		name: "commune",
		id: "commune",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឃុំ/សង្កាត់",	
			onChange: function() {
				commune = dijit.byId('commune').get('value');
				if(commune==-1){
					showPopupCommune();
				}
				else{
					filterVillage();
				}
			  }
		}, "commune");		 

	}catch(e){
		alert(e);
	}
});*/

dojo.ready(function(){
	Checkchange();
});
var oldemail ='<?php echo $email;?>';
var loadFile = function(event) {
    var output = document.getElementById('profile_wiew');
    output.src = URL.createObjectURL(event.target.files[0]);
  };

  function checkSpcialChar(event){
	    if(((event.keyCode > 64 && event.keyCode < 91) || event.keyCode == 189 || event.keyCode == 45 || (event.keyCode > 96 && event.keyCode < 123) || event.keyCode == 8 || (event.keyCode >= 48 && event.keyCode <= 57))){
	        event.returnValue = true;
	        return;
	     }
	     event.returnValue = false;
	  }
  var check=0;
  var url_email = '<?php echo $this->baseUrl();?>/index/checkmail';
  function checkMail(){
  	email = $('#email').val();
  	 var message = document.getElementById('error');
  	$.ajax({
          url: url_email,
          type: "post",
          data: {'email':email},
          success: function(data){
              val = $.parseJSON(data);
  				if(val==1){
  	  				if(email== oldemail){
  	  	  				message.innerHTML = "";
  	  					check=0;
  	  				}else{
  					 message.innerHTML = "  Email already use !";
   					dijit.byId('email').focus();
   					check=1;
  	  				}
  				}
  				else{
  					message.innerHTML = "";
  					check=0;
  				}

  			},
  			error: function(err) {
  				alert(err);
  			}
  		});
  }
  function Checkchange(){
	  if (dojo.byId("check_change").checked){
		  dijit.byId('password').set('required',true); 
		  dijit.byId('password').set('readonly',false); 
		 
	  }else{
		  $('#password').val('');
		  dijit.byId('password').set('required',false); 
		  dijit.byId('password').set('readonly',true); 
	  }
  }
</script>








