<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("CLIENT_LIST"));
$frm = $this->frm_search;
$frms=$this->frm_client;
$url_delete =$this->url(array('module'=>'group','controller'=>'index','action'=>'delete'));
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
<table>
   <tr>  
      <td><?php echo $frm->getElement("adv_search");?></td>
       <td><?php echo $frm->getElement('status');?></td>
       <td><?php echo $frm->getElement('start_date');?></td>
      <td><?php echo $frm->getElement('end_date');?></td>
      <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	  <td>	<input type="submit" value="show_all" onClick="resetForm();" label="<?php echo $tr->translate('SHOW_ALL');?>" id="show_all" dojoType="dijit.form.Button" name="show_all" />
	 	 <input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" /></td>
	  </td>
   </tr>
</table>  
<?php echo $this->list;?> 
</form>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
dojo.ready(function(){
	
});


function  resetForm(){
	var datenow = '<?php echo date("Y-m-d");?>';
	dijit.byId('adv_search').attr('value','');
	dijit.byId('status_search').set('value','-1');
}
function deleteRecord(url){
	 id = recordid;
	 window.location.href = url+'/id/'+id;
}
function showDeleteForm(id){
	//id = dijit.byId('recorddelete').get('value');
	if(id==''){
		alert("No record selected for delete.");
		dijit.byId('deleteForm').hide();
	}else{
		dijit.byId('deleteForm').show();
		recordid = id;
	}
}
function closeForm(){
	dijit.byId('deleteForm').hide();
}
</script> 
<div class="dijitHidden">
<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'តើអ្នកពិតជាលុបទិន្នន័យនេះមែនទេ?'"  id="deleteForm" style="width:350px;" >
	<div style=" text-align: center;">
		<h4>តើអ្នកពិតជាលុបទិន្នន័យនេះមែនទេ?</h4>
		<button onclick="deleteRecord('<?php echo $url_delete;?>')" iconclass="dijitIconDelete" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("DELETE");?></button>
		<button onclick="closeForm();" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("CANCEL");?></button>
	</div>
</div>
</div>