<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('CUSTOMER_PROFILE')); 
	echo $this->headTitle(''); 
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មិនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កញ្ញា","08"=>"កក្កដា","09"=>"សីហា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="dojo/method" event="onSubmit">			
	if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<style>
.b{ font-weight: bold; }
</style>
<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox");
dojo.ready(function(){
	 
}); 
 
</script>
 
		<table width="100%">
		      <tr>
		           <td></td>
			       <td>
						<div class="menureport">
							<ul>
								<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
								<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
								<li class="excel"><a href="#"  title="Export"  onclick="exportExcel();"></a></li>
							</ul>
						</div>
			      </td>
			</tr>
		   </table>
		<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
			
			<div id="divPrint">
				<style>
		   			tr.header-line{
		   				font-size: 16px;
					}
		   		</style>
				<table width="100%" style="font-size:12px;font-family:'Times New Roman','Khmer OS Battambang';"> 
					<tr>
						<td>
						   <table width="100%" >
						   			<tr>
										<td width="28%" align="left">
											<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.jpg'?>"><br /><br >
										</td>
										<td align="center" width="44%"  >
											<strong style="font-weight:bold;color:#000; font-size: 18px;font-family:'Times New Roman','Khmer MEF2';"><?php echo $tr->translate("CUSTOMER_PROFILE"); ?></strong><br />
											<span style="font-weight: bold;font-size: 12px;">&nbsp;<?php echo $tr->translate("FOR_DATE");?>&nbsp;<?php echo date("d");?>&nbsp;ខែ&nbsp;<?php echo $month[date("m")];?>&nbsp;ឆ្នាំ &nbsp;<?php echo date("Y");?></span><br /><br />
										</td>
										<td width="28%" align="right">
										</td>
									</tr>
									<tr>   
						     	    	<td colspan="3" align="center">
											 <div style="width:100%; height:140px;padding:3px;"><img src="<?php echo $this->baseUrl();?>/images/<?php if(!empty($this->client_list['photo_name'])){ echo $this->client_list['photo_name'];}else{ echo "no-profile.png";}?>" style="width:120px;height:140px;     border: solid 1px #ccc;"/></div>
						      		    </td>
						      		  </tr>
						   </table>
						   <?php $sex='';
									      if($this->client_list['sex']==1){
									      	$sex=$tr->translate("MALE");
										  }else{
										  	$sex=$tr->translate("FEMALE");
										  }
									?>
					      	<table  cellspacing="5"  style="background:#fff;margin: 0 auto;width: 100%;font-size:16px;font-family:'Times New Roman','Khmer OS Battambang';" >
					      		<tr class="header-line">
					     	         <td colspan="6" style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("CUSTOMER_PROFILE");?></strong></td>
					     	    </tr>
					      		<tr >
					      		      <td style="width:80%; vertical-align: top;" colspan="4">
					      		         <table width="100%" style="font-size:16px;">
					      		               <tr>
					      		                   <td><?php echo $tr->translate("NAME_KH");?>:</td>
					      		                   <td><label><?php echo $this->client_list['name_kh'];?></label></td>
					      		                   <td> <?php echo $tr->translate("SEX");?>:&nbsp;</td>
					      		                   <td><label><?php echo $sex?></label></td>
					      		               </tr>
					      		               <tr>
					      		               	   <td><?php echo $tr->translate("NATIONALITY");?>:</td>
					      		                   <td><label><?php echo $this->client_list['nationality'];?></label></td>
					      		                   <td> <?php echo $tr->translate("AGE");?>:&nbsp; </td>
					      		                   <td><label><?php echo $this->client_list['age'];?></label></td>
					      		                   
					      		               </tr>
					      		               <tr>
					      		              	  <td><?php echo $tr->translate("NATIONAL_ID");?>:</td>
					      		                  <td><label><?php echo $this->client_list['nation_id'];?></label></td>
					      		                  <td> <?php echo $tr->translate("DATE_IN");?>:&nbsp; </td>
					      		                  <td><label><?php echo date("d",strtotime($this->client_list['nation_id_issue_date']));?>&nbsp;ខែ&nbsp;<?php echo $month[date("m",strtotime($this->client_list['nation_id_issue_date']))];?>&nbsp;ឆ្នាំ &nbsp;<?php echo date("Y",strtotime($this->client_list['nation_id_issue_date']));?></label></td>
					      		               </tr>
					      		               <tr>
					      		               		<td><?php echo $tr->translate("PHONE");?>:&nbsp;</td>
					      		                  	<td><label><?php echo $this->client_list['phone'];?></label></td>
					      		                  	<td><?php echo $tr->translate("EMAIL");?>:&nbsp; </td>
					      		               		<td><label><?php echo $this->client_list['email'];?></label></td>
					      		               </tr>
					      		         </table>
									</td>
					      		</tr>
					      		<tr >  </tr>
					      		<tr> </tr>
					      		
					      	</table>
					     	<table width="100%" style="margin:0 auto;font-size:16px;" cellspacing="5">
					      		<tr class="header-line">
					      			<td colspan="6"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("RELEVANT_STAKEHOLDER");?></strong></td>
					      		</tr>
					      		<?php $plot_sex='';
									      if($this->client_list['ksex']==1){
									      	$plot_sex=$tr->translate("MALE");
										  }else{
										  	$plot_sex=$tr->translate("FEMALE");
										  }
									?>
					      		<tr>
					      			<td><?php echo $tr->translate("NAME_KH");?>:</td>
									<td><label><?php echo $this->client_list['hname_kh'];?></label> </td>
									<td><?php echo $tr->translate("SEX");?>:</td>
									<td><label><?php echo $plot_sex; ?></label></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("NATIONALITY");?>:</td>
									<td><label><?php echo $this->client_list['p_nationality'];?></label> </td>
									<td><?php echo $tr->translate("AGE");?>:</td>
									<td><label><?php echo $this->client_list['p_age'];?></label> </td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("NATIONAL_ID");?>:</td>
									<td><label><?php echo $this->client_list['rid_no'];?></label> </td>
									<td><?php echo $tr->translate("DATE_IN");?>:</td>
									<td><label><?php echo date("d",strtotime($this->client_list['p_nation_issue_date']));?>&nbsp;ខែ&nbsp;<?php echo $month[date("m",strtotime($this->client_list['p_nation_issue_date']))];?>&nbsp;ឆ្នាំ &nbsp;<?php echo date("Y",strtotime($this->client_list['p_nation_issue_date']));?></label> </td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("PHONE");?>:</td>
									<td><label><?php echo $this->client_list['lphone'];?></label> </td>
									<td><?php echo $tr->translate("IS");?>:</td>
									<td><label><?php echo $this->client_list['relevent'];?></label> </td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("WITNESS_NAME");?>:</td>
									<td><label><?php echo $this->client_list['arid_no'];?></label> </td>
									<td><?php echo $tr->translate("WITNESS_NATION_ID");?>:</td>
									<td><label><?php echo $this->client_list['refe_nation_id'];?></label> </td>
								</tr>
					      		<tr><td></td></tr>
					      		<tr class="header-line">
					      			<td colspan="6"​ style="border-bottom:1px solid #ddd;" class="b"><strong><?php echo $tr->translate("CURRENT_ADDRESS");?></strong></td>
					      		</tr>
					      		<tr>
					      			<td colspan="6"><?php echo $this->client_list['current_address'];?></td>
									
								</tr>
								<tr><td></td></tr>
							</table>
		 
					   </td>
					</tr>
	   </table>
	   </div>
	 </div>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>

